FibrasIntegracion/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('interfaces/',include(('interfaces.urls','interfaces'), namespace='interfaces')),


]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from bases import views
from bases.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='base/login.html'),
        name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='base/login.html'),
        name='logout'),
]

interfaces/urls.py
from django.urls import path
from interfaces.views import ClientesOdooView, ClientesOdooNew, ClientesOdooEdit,\
    ClientesOchoquinceView, dashboard,DeudaVencidaClientesDetalleView

urlpatterns = [

    path('clientes/', ClientesOdooView.as_view(), name="clientes_list"),
    path('clientes/new', ClientesOdooNew.as_view(), name="cliente_new"),
    path('clientes/edit/<int:pk>', ClientesOdooEdit.as_view(), name="clientes_edit"),

    path('clientes/gateway', ClientesOchoquinceView.buscarClientes, name='clientes_list_gateway'),
    path('clientes/integra', ClientesOchoquinceView.integraCliente, name='clientes_list_integra'),
    path('clientes/clideuda', DeudaVencidaClientesDetalleView.as_view(), name='clientes_deuda'),
        
    # path('administracion/dashboard', DeudaVencidaClientesView.as_view(), name="dashboard_deuda_vencida"),
    path('administracion/dashboard', dashboard.DeudaVencidaClientesView, name="dashboard_deuda_vencida"),
    

    # path('buscar/', views.buscar),
    # path('gw815/', views.gw815),
    # path('cliodoo', views.lista_cliente_odoo),

]

interfaces/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

class AccountAccount(models.Model):
    create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True, related_name='create_uid%(app_label)s_%(class)s_related')
    internal_type = models.CharField(max_length=20, blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=20)
    deprecated = models.BooleanField(blank=True, null=True)
    currency = models.ForeignKey('ResCurrency', models.DO_NOTHING, blank=True, null=True, related_name='currency%(app_label)s_%(class)s_related')
    company = models.ForeignKey('ResCompany', models.DO_NOTHING, related_name='company%(app_label)s_%(class)s_related')
    write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True, related_name='write_uid%(app_label)s_%(class)s_related')
    note = models.TextField(blank=True, null=True)
    code = models.CharField(max_length=64)
    write_date = models.DateTimeField(blank=True, null=True)
    user_type = models.ForeignKey('AccountAccountType', models.DO_NOTHING, related_name='usertype%(app_label)s_%(class)s_related')
    last_time_entries_checked = models.DateTimeField(blank=True, null=True)
    reconcile = models.BooleanField(blank=True, null=True)
    afip_activity = models.ForeignKey('AfipActivity', models.DO_NOTHING, blank=True, null=True, related_name='afip_activity%(app_label)s_%(class)s_related')
    vat_f2002_category = models.ForeignKey('AfipVatF2002Category', models.DO_NOTHING, blank=True, null=True, related_name='vat_f2002_category%(app_label)s_%(class)s_related')

    class Meta:
        managed = False
        db_table = 'account_account'
        unique_together = (('code', 'company'),)


class AccountAccountAccountTag(models.Model):
    account_account = models.ForeignKey(AccountAccount, models.DO_NOTHING, related_name='account_account%(app_label)s_%(class)s_related')
    account_account_tag = models.ForeignKey('AccountAccountTag', models.DO_NOTHING, related_name='account_account_tag%(app_label)s_%(class)s_related')

    class Meta:
        managed = False
        db_table = 'account_account_account_tag'
        unique_together = (('account_account', 'account_account_tag'),)


class AccountAccountFinancialReport(models.Model):
    report_line = models.ForeignKey('AccountFinancialReport', models.DO_NOTHING,related_name='report_line%(app_label)s_%(class)s_related')
    account = models.ForeignKey(AccountAccount, models.DO_NOTHING, related_name='account%(app_label)s_%(class)s_related')

    class Meta:
        managed = False
        db_table = 'account_account_financial_report'
        unique_together = (('report_line', 'account'),)


class AccountAccountFinancialReportType(models.Model):
    report = models.ForeignKey('AccountFinancialReport', models.DO_NOTHING)
    account_type = models.ForeignKey('AccountAccountType', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_financial_report_type'
        unique_together = (('report', 'account_type'),)


class AccountAccountTag(models.Model):
    create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True, related_name='create_uid%(app_label)s_%(class)s_related')
    applicability = models.CharField(max_length=20)
    create_date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=20)
    color = models.IntegerField(blank=True, null=True)
    write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True, related_name='write_uid%(app_label)s_%(class)s_related')
    write_date = models.DateTimeField(blank=True, null=True)
    jurisdiction_code = models.CharField(max_length=3, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'account_account_tag'


class AccountAccountTagAccountTaxTemplateRel(models.Model):
    account_tax_template = models.ForeignKey('AccountTaxTemplate', models.DO_NOTHING)
    account_account_tag = models.ForeignKey(AccountAccountTag, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_tag_account_tax_template_rel'
        unique_together = (('account_tax_template', 'account_account_tag'),)


class AccountAccountTaxDefaultRel(models.Model):
    account = models.ForeignKey(AccountAccount, models.DO_NOTHING)
    tax = models.ForeignKey('AccountTax', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_tax_default_rel'
        unique_together = (('account', 'tax'),)


class AccountAccountTemplate(models.Model):
    create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True, related_name='create_uid%(app_label)s_%(class)s_related')
    code = models.CharField(max_length=64)
    create_date = models.DateTimeField(blank=True, null=True)
    reconcile = models.BooleanField(blank=True, null=True)
    name = models.CharField(max_length=20)
    chart_template = models.ForeignKey('AccountChartTemplate', models.DO_NOTHING, blank=True, null=True)
    write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True, related_name='write_uid%(app_label)s_%(class)s_related')
    currency = models.ForeignKey('ResCurrency', models.DO_NOTHING, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    nocreate = models.BooleanField(blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    user_type = models.ForeignKey('AccountAccountType', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_template'


class AccountAccountTemplateAccountTag(models.Model):
    account_account_template = models.ForeignKey(AccountAccountTemplate, models.DO_NOTHING)
    account_account_tag = models.ForeignKey(AccountAccountTag, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_template_account_tag'
        unique_together = (('account_account_template', 'account_account_tag'),)


class AccountAccountTemplateTaxRel(models.Model):
    account = models.ForeignKey(AccountAccountTemplate, models.DO_NOTHING)
    tax = models.ForeignKey('AccountTaxTemplate', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_template_tax_rel'
        unique_together = (('account', 'tax'),)


class AccountAccountType(models.Model):
    create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True, related_name='create_uid%(app_label)s_%(class)s_related')
    create_date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=20)
    write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True, related_name='write_uid%(app_label)s_%(class)s_related')
    note = models.TextField(blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    include_initial_balance = models.BooleanField(blank=True, null=True)
    type = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'account_account_type'


class AccountAccountTypeRel(models.Model):
    journal = models.ForeignKey('AccountJournal', models.DO_NOTHING)
    account = models.ForeignKey(AccountAccount, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_account_type_rel'
        unique_together = (('journal', 'account'),)


class AccountAgedTrialBalance(models.Model):
    create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True, related_name='create_uid%(app_label)s_%(class)s_related')
    create_date = models.DateTimeField(blank=True, null=True)
    period_length = models.IntegerField()
    date_from = models.DateField(blank=True, null=True)
    result_selection = models.CharField(max_length=20)
    company = models.ForeignKey('ResCompany', models.DO_NOTHING, blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    date_to = models.DateField(blank=True, null=True)
    write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True, related_name='write_uid%(app_label)s_%(class)s_related')
    target_move = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'account_aged_trial_balance'


class AccountAgedTrialBalanceAccountJournalRel(models.Model):
    account_aged_trial_balance = models.ForeignKey(AccountAgedTrialBalance, models.DO_NOTHING)
    account_journal = models.ForeignKey('AccountJournal', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_aged_trial_balance_account_journal_rel'
        unique_together = (('account_aged_trial_balance', 'account_journal'),)


class AccountAnalyticAccount(models.Model):
    code = models.CharField(max_length=20, blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=20)
    create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True, related_name='create_uid%(app_label)s_%(class)s_related')
    message_last_post = models.DateTimeField(blank=True, null=True)

interfaces/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import F, Sum
from django.db.models.functions import Round


from interfaces.models import ResPartner, AccountInvoice
from interfaces.forms import ClientesForm
from interfaces.gateway815 import ochoquince

# from django.http import HttpResponse

# from interfaces.gateway815 import ochoquince
# from interfaces.odoo import fnOdoo,Odoo

# Create your views here.

class ClientesOdooView(LoginRequiredMixin,generic.ListView):
    model = ResPartner
    queryset = ResPartner.objects.filter(customer=True, employee=False)
    template_name = "interfaces/clientes_list.html"
    context_object_name = "obj" # renombramos el nombre del objeto para tener mas control. Por defecto Django lo llama "object"
    login_url = "bases:login" # definimos la url de login por si no lo estuvieramos

class ClientesOdooNew(LoginRequiredMixin,generic.CreateView):
    model=ResPartner
    template_name = "interfaces/clientes_form.html"
    context_object_name = "obj"
    form_class = ClientesForm
    success_url = reverse_lazy("interfaces:clientes_list")
    success_message="Cliente creado satisfactoriamente"
    login_url="bases:login"
    
    def form_valid(self, form):  # sobreescribimos este metodo para enviarle el token id del usuario logueado
        form.instance.uc = self.request.user # tomamos el usuario loqueado y se lo mandamos a la instancia
        return super().form_valid(form) # si esta validado retornamos y sobreescribimos la propiedad form_valid del padre con el formulario modificado

class ClientesOdooEdit(LoginRequiredMixin,generic.UpdateView):
    model=ResPartner
    template_name = "interfaces/clientes_form.html"
    context_object_name = "obj"
    form_class = ClientesForm
    success_url = reverse_lazy("interfaces:clientes_list")
    success_message="Cliente actualizado satisfactoriamente"
    login_url="bases:login"
    
    def form_valid(self, form):  # sobreescribimos este metodo para enviarle el token id del usuario logueado
        form.instance.um = self.request.user.id # tomamos el usuario loqueado y se lo mandamos a la instancia
        return super().form_valid(form) # si esta validado retornamos y sobreescribimos la propiedad form_valid del padre con el formulario modificado


# class DeudaVencidaClientesView(LoginRequiredMixin,generic.ListView):
#     model = AccountInvoice
#     queryset = AccountInvoice.objects.filter(state='open', journal_id=11).aggregate(sum=Round(Sum(F('residual'))))
#     template_name = "interfaces/dashboard.html"
#     context_object_name = "obj" # renombramos el nombre del objeto para tener mas control. Por defecto Django lo llama "object"
#     login_url = "bases:login" # definimos la url de login por si no lo estuvieramos

class dashboard(LoginRequiredMixin):

    def DeudaVencidaClientesView(request):
        model = AccountInvoice
        deuda = AccountInvoice.objects.filter(state='open', journal_id=11).aggregate(sum=Round(Sum(F('residual'))))
        template_name = "interfaces/dashboard.html"
        # context_object_name = "obj" # renombramos el nombre del objeto para tener mas control. Por defecto Django lo llama "object"
        # login_url = "bases:login" # definimos la url de login por si no lo estuvieramos
        return render(request,template_name,{'obj': deuda})


class DeudaVencidaClientesDetalleView(LoginRequiredMixin,generic.ListView):
    # model = AccountInvoice.objects.annotate(deuda=Sum(F('residual'))).filter(state='open', journal_id=11)
    model = AccountInvoice
    queryset = AccountInvoice.objects.filter(state='open', journal_id=11).values('partner_id__ref', 'partner_id__name','partner_id__phone','partner_id__mobile').annotate(deuda=Round(Sum(F('residual'))))
    # queryset = AccountInvoice.objects.filter(state='open', journal_id=11).values('partner_id').annotate(sum=Round(Sum(F('residual'))))
    template_name = "interfaces/clientes_deuda.html"
    context_object_name = "obj" # renombramos el nombre del objeto para tener mas control. Por defecto Django lo llama "object"
    login_url = "bases:login" # definimos la url de login por si no lo estuvieramos    

# class ClientesOchoquinceView(LoginRequiredMixin):
class ClientesOchoquinceView():
    
    def buscarClientes(request):
        gw=ochoquince()
        token=gw.obtenerToken()
        listaClientes = gw.obtenerClientes(token)
     
        template_name = "interfaces/clientes_gw_list.html"
        return render(request,template_name,{'cliente': listaClientes})

    def integraCliente(request):
        gw=ochoquince()
        token=gw.obtenerToken()
        listaCliGW = gw.obtenerClientes(token)
        listaCliOdoo = ResPartner.objects.filter(customer=True, parent_id=None)
        listaClientes=[]

        for cliOdoo in listaCliOdoo:

            for cliGW in listaCliGW:

                if cliOdoo.ref == cliGW[4] and (cliOdoo.ref != None or cliGW[4] != None):
                    listaClientes.append([cliOdoo.ref,cliOdoo.name,cliGW[1],cliGW[0]])   
                    break
        
        for cliOdoo in listaCliOdoo:
            if cliOdoo.ref == None:
                listaClientes.append(['Falta NroCliente Odoo',cliOdoo.name,'','']) 

        for cliGW in listaCliGW:
            if cliGW[4] == None:
                listaClientes.append(['Falta Conector GW','',cliGW[1],cliGW[0]])  
        
      
        template_name = "interfaces/clientes_integracli_list.html"
        return render(request,template_name,{'cliente': listaClientes})

interfaces/templates/interfaces/clientes_deuda.html
{% extends 'base/base.html' %}
{% load humanize %}

{% block page_content %}

<div class="card shadow mb-4">
    {% csrf_token %}
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Deuda Vencida</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'interfaces:cliente_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
          <!-- <a class="dropdown-item" href="#">Another action</a> -->
          <div class="dropdown-divider"></div>
          <!-- <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay clientes</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>NroCliente</th>
              <th>Nombre</th>
              <th>Telefono</th>
              <th>Celular</th>
              <th>Deuda</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.partner_id__ref }}</td>
                  <td>{{ item.partner_id__name }}</td>
                  <td>{{ item.partner_id__phone }}</td>
                  <td>{{ item.partner_id__mobile }}</td>
                  <td>${{ item.deuda }}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock %}

interfaces/templates/interfaces/clientes_list.html
{% extends 'base/base.html' %}

{% block page_content %}

<div class="card shadow mb-4">
    {% csrf_token %}
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes Odoo</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <!-- <a class="dropdown-item" onclick="return abrir_modal('{% url 'interfaces:cliente_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a> -->
          <a class="dropdown-item" href="{% url 'interfaces:cliente_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
          <!-- <a class="dropdown-item" href="#">Another action</a> -->
          <!-- <div class="dropdown-divider"></div> -->
          <!-- <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay clientes</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>ID</th>
              <th>Nombre</th>
              <th>Estado</th>
              <th>F. Creado</th>
              <th>F. Modif.</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.ref }}</td>
                  <td>{{ item.name }}</td>
                  {% if item.active %}
                   <td><span class="badge badge-success">Activo</span></td>
                  {% else %}
                   <td><span class="badge badge-danger">Inactivo</span></td>
                  {% endif %}
                      <!-- {{ item.active|yesno:"Activo,Inactivo" }}</td> -->
                  <td>{{ item.create_date|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.write_date|date:"d/m/Y H:i:s" }}</td>
                  <td>
                    <a href="{% url 'interfaces:clientes_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> 
                    <a href="#" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock %}

interfaces/templates/interfaces/dashboard.html
{% extends 'base/base.html' %}
{% load humanize %}

{% block page_content %}

<!-- Deuda de CLientes -->
<div class="col-xl-3 col-md-6 mb-4">
  {% csrf_token %}
  <div class="card border-left-danger shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Deuda Clientes</div>
          {% if obj %}
            {% for key, value in obj.items %}
              <div class="h5 mb-0 font-weight-bold text-gray-800">${{value|intcomma }}</div>
            {% endfor %}
          {% else %}
            <div class="h5 mb-0 font-weight-bold text-gray-800">$0.00</div>
          {% endif %}
        </div>

      </a>
      <a href="{% url 'interfaces:clientes_deuda' %}" class="btn btn-info btn-circle btn-sm">
        <i class="fas fa-info-circle"></i>
      </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js_page %}
{% endblock %}